# Generated by Django 4.1.6 on 2023-02-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hhc_id', models.CharField(max_length=50)),
                ('patients_name', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=50)),
                ('location', models.CharField(max_length=500)),
                ('is_deleted', models.CharField(max_length=10)),
            ],
        ),
    ]
